#####################################
#                                   #
#  Makefile for AutoParkingC++
#  Generated by Bloodshed Dev-C++   #
#                                   #
#####################################


# Compiler
CC=g++
# Parameters given to the compiler
CFLAGS=-s   -IC:\ARQUIV~1\DEV-C_~1\INCLUDE\ -IC:\ARQUIV~1\DEV-C_~1\INCLUDE\G__~1 -IC:\ARQUIV~1\DEV-C_~1\INCLUDE\ -LC:\ARQUIV~1\DEV-C_~1\LIB\ -BC:\ARQUIV~1\DEV-C_~1\BIN\  
# Output filename (*.exe)
OUTPUT="AutoParkingC++.exe"

# Source files
SRCS="C:\Alex\AutoParking\cenario.cpp" "C:\Alex\AutoParking\interface.cpp" 
# Output object files (*.o)
OBJS="C:\Alex\AutoParking\cenario.o" "C:\Alex\AutoParking\interface.o" -lopengl32 -lglut32 -lglu32 "C:\Alex\AutoParking\rsrc.o"

# Standard targets

all: compile_res
	$(CC) -c $(SRCS) $(CFLAGS)
	$(CC) -o $(OUTPUT) $(OBJS) $(CFLAGS)

compile_res:
	windres --include-dir C:\ARQUIV~1\DEV-C_~1\INCLUDE\ --include-dir C:\ARQUIV~1\DEV-C_~1\INCLUDE\G__~1 --include-dir C:\ARQUIV~1\DEV-C_~1\INCLUDE\ --use-temp-file -I rc -O coff -i "C:\ALEX\AUTOPA~1\RSRC.RC" -o "C:\ALEX\AUTOPA~1\RSRC.o"

test: all
	./$(OUTPUT)

clean:
	del *.o

mrproper: clean

